# These tasks will be merged into deployment graph. Here you
# can specify new tasks for any roles, even built-in ones.

- id: gcs_copy_keys
  type: copy_files
  role: 'cinder'
  required_for: [pre_deployment_end]
  requires: [generate_keys]
  parameters:
    files:
      - src: /root/gcs_key
        dst: /root/gcs_key
    permissions: '0600'
    dir_permissions: '0700'

- id: gcs_cinder_conf
  type: puppet
  role: 'cinder'
  requires: [openstack-cinder]
  parameters:
    puppet_manifest: gcs_cinder_conf.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 300

#  requires: [deploy_start] # version 1.0.0
#  required_for: [deploy_end]
#- id: gcs-plugin-post-deployment-sh
#  type: shell
#  role: [gcs-plugin_role]
#  version: 2.0.0
#  cross-depends:
#    - name: post_deployment_start
#  cross-depended-by:
#    - name: post_deployment_end
# #  requires: [post_deployment_start]
# #  required_for: [post_deployment_end]
#  parameters:
#    cmd: echo post_deployment_task_executed > /tmp/post_deployment
#    retries: 3
#    interval: 20
#    timeout: 180

#- id: gcs-plugin-pre-deployment-sh
#  type: shell
#  role: [gcs-plugin_role]
#  version: 2.0.0
#  cross-depends:
#    - name: pre_deployment_start
#  cross-depended-by:
#    - name: pre_deployment_end
# #  requires: [pre_deployment_start]
# #  required_for: [pre_deployment_end]
#  parameters:
#    cmd: echo pre_deployment_task_executed > /tmp/pre_deployment
#    retries: 3
#    interval: 20
#    timeout: 180
